function signal_sampling_gui
% Signal Sampling and Analysis GUI

% Create the GUI figure
fig = figure('Name', 'Signal Sampling and Analysis', ...
             'Units', 'normalized', ...
             'Position', [0.2, 0.2, 0.6, 0.6]);

% Create the UI controls
uicontrol('Parent', fig, ...
          'Style', 'text', ...
          'String', 'Original Signal', ...
          'Units', 'normalized', ...
          'Position', [0.05, 0.9, 0.2, 0.05], ...
          'HorizontalAlignment', 'left');

uicontrol('Parent', fig, ...
          'Style', 'text', ...
          'String', 'Sampled Signal', ...
          'Units', 'normalized', ...
          'Position', [0.35, 0.9, 0.2, 0.05], ...
          'HorizontalAlignment', 'left');

uicontrol('Parent', fig, ...
          'Style', 'text', ...
          'String', 'Sampling Frequency:', ...
          'Units', 'normalized', ...
          'Position', [0.05, 0.8, 0.2, 0.05], ...
          'HorizontalAlignment', 'left');

% Create the sampling frequency input field
sampling_freq_input = uicontrol('Parent', fig, ...
                                'Style', 'edit', ...
                                'Units', 'normalized', ...
                                'Position', [0.25, 0.8, 0.1, 0.05], ...
                                'String', '1000');

uicontrol('Parent', fig, ...
          'Style', 'text', ...
          'String', 'Hz', ...
          'Units', 'normalized', ...
          'Position', [0.35, 0.8, 0.05, 0.05], ...
          'HorizontalAlignment', 'left');

uicontrol('Parent', fig, ...
          'Style', 'pushbutton', ...
          'String', 'Sample Signal', ...
          'Units', 'normalized', ...
          'Position', [0.05, 0.7, 0.2, 0.05], ...
          'Callback', @sample_signal_callback);

% Create the original signal axes
orig_signal_axes = axes('Parent', fig, ...
                        'Units', 'normalized', ...
                        'Position', [0.05, 0.2, 0.2, 0.45]);

% Create the sampled signal axes
samp_signal_axes = axes('Parent', fig, ...
                        'Units', 'normalized', ...
                        'Position', [0.35, 0.2, 0.2, 0.45]);

% Create the frequency domain axes
freq_domain_axes = axes('Parent', fig, ...
                        'Units', 'normalized', ...
                        'Position', [0.65, 0.2, 0.3, 0.7]);

% Define the initial signal parameters
t = 0:0.001:1;  % Time vector
f = 10;         % Signal frequency
A = 1;          % Signal amplitude
phi = 0;        % Signal phase

% Plot the original signal
orig_signal = A*sin(2*pi*f*t + phi);
plot(orig_signal_axes, t, orig_signal);
xlabel(orig_signal_axes, 'Time (s)');
ylabel(orig_signal_axes, 'Amplitude');
title(orig_signal_axes, 'Original Signal');

% Define the function to sample the signal
function sample_signal_callback(~, ~)
    % Get the sampling frequency from the input field
    fs = str2double(get(sampling_freq_input, 'String'));
    
    % Calculate the sampling period
    Ts = 1/fs;
    
    % Calculate the number of samples
    num_samples = floor(length(t)/fs);
    
    % Sample the signal
    samp_signal = zeros(1, num_samples);
    for i = 1:num_samples
        samp_signal(i) = A*sin(2*pi*f*(i-1)*Ts + phi);
    end
    
    % Plot the sampled signal
    plot(samp_signal_axes, 0:Ts:(num_samples-1)*Ts, samp_signal);
    xlabel(samp_signal_axes, 'Time (s)');
    ylabel(samp_signal_axes, 'Amplitude');
    title(samp_signal_axes, sprintf('Sampled Signal (fs = %d Hz)', fs));
    
    % Calculate the frequency spectrum of the sampled signal
    freq_spectrum = abs(fft(samp_signal));
    freq_axis = linspace(0, fs, length(freq_spectrum));
    
    % Plot the frequency spectrum
    plot(freq_domain_axes, freq_axis, freq_spectrum);
    xlabel(freq_domain_axes, 'Frequency (Hz)');
    ylabel(freq_domain_axes, 'Amplitude');
    title(freq_domain_axes, 'Frequency Spectrum');
end

end