function Hd = xishu
%XISHU Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 17-Jun-2023 20:57:39

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 200;  % Sampling Frequency

N     = 200;  % Order
Fpass = 8;    % Passband Frequency
Fstop = 12;   % Stopband Frequency
Wpass = 1;    % Passband Weight
Wstop = 80;   % Stopband Weight
dens  = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
    {dens});
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
